import Head from 'next/head'
import Image from 'next/image'
import { Box } from "@chakra-ui/react";

import PageWrapper, { Layout } from "components/wrappers/Page"

HomeHero.getLayout = function getLayout(page: React.ReactElement) {
  return <Layout variant="logoOnly" >{page}</Layout>;
};

export default function HomeHero() {
  return (
    <PageWrapper title="Decentralized Social Clearing House">
      <Head>
        <title>Decentralized Social Clearing House</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box
        id="main-content"
        pt={{ base: 16, md: 8 }}
        p="4"
      >
        <footer >
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span >
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </Box>
    </PageWrapper>
  );
}
